site_name: Jinja UI
site_url: https://tameronline.github.io/jinja-ui/
repo_url: https://github.com/TamerOnLine/jinja-ui
repo_name: GitHub

docs_dir: src/docs

theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.tabs
    - search.highlight
    - content.code.copy
    - toc.integrate
  palette:
    scheme: default
    primary: blue
    accent: light blue
  icon:
    repo: fontawesome/brands/github

extra:
  logo: images/logo.png
  favicon: images/favicon.ico

nav:
  - ğŸ  Home: index.md
  - ğŸŒ GitHub Pages: gh-pages.md
  #- ğŸ“– Getting Started:
  #    - Installation: getting-started/installation.md
  #    - Quick Start: getting-started/quickstart.md
  #- âš™ï¸ CLI Usage: cli/usage.md
  #- ğŸ§± Architecture: architecture.md
  #- ğŸ“¦ API Reference:
  #    - CLI Module: api/cli.md
  #    - Utils Module: api/utils.md
  #- â“ FAQ: faq.md
  #- ğŸ‘¥ Contributing: contributing.md
  - ğŸ“œ License: license.md
  - ğŸ§‘â€ğŸ’» About: about.md

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - tables
  - toc:
      permalink: true
